### ISSUE TITLE
Zetta server is not accessible if there is not an AllJoyn service

### ISSUE THREAD

**Issue by wongni** [landlessness/zetta-dynamic-alljoyn-driver#5]
When there is an AllJoyn service running in the same network, the driver prints out the following and http://browser.zettajs.io/ is able to connect to the server. 

Feb-08-2016 11:05:09 [server] Server (Connected-Life) Connected-Life listening on http://127.0.0.1:1337
Feb-08-2016 11:05:10 [scout] Device (dynamicAllJoyn) ebaf11dd-206b-47d3-899b-2d22297d98e1 was provisioned from registry.
Feb-08-2016 11:05:11 [peer-client] WebSocket to peer established (ws://schneider-e1-dev.apigee.net/schneider-v1/peers/Connected-Life)
Feb-08-2016 11:05:11 [peer-client] Peer connection established (ws://schneider-e1-dev.apigee.net/schneider-v1/peers/Connected-Life)

However, if there is no AllJoyn service in the network, http://browser.zettajs.io/ is not able to connect to the server. 

How to reproduce
1. Make sure there is no AllJoyn service running in the network
2. # node example/server.js
3. Open http://browser.zettajs.io/#/overview?url=http:%2F%2F127.0.0.1:1337 in a browser

![image](https://cloud.githubusercontent.com/assets/11528277/12891185/d26be7b6-ce54-11e5-8aa3-f240cbce7cdf.png)

**Comment by landlessness** [comment]
fixed by commit 03ee9f704fd5bb9564ab12818ef7d5c61f451142
